### ISSUE TITLE
Capstone Project Morning Review

### ISSUE THREAD

**Issue by BonkeGcobo** [Hombre2014/Conference-page#1]
Great Job So Far, there are a few changes you can make to make your project perfect:

1) In the sponsor section, add a hover property on the logo
2) Make the menu items, link to different sections of the page.

**Comment by AmaduKamara** [comment]
Great work done so far.
- It will be nice you divide the two sections in the footer to have like 30% 70% width. The logo is left and the text is on the right.

**Comment by Hombre2014** [comment]
Thanks for the suggestions. They have been implemented.
